In [2]:
import numpy as np
import scipy

Zad 1

a) $det(A) = 0$ -> macierz osobliwa

b) $det(A) = \frac{58867}{1000000} = 0.058867$
$$
A^{-1} = 
\begin{bmatrix}
\frac{145500}{1369} & \frac{290000}{1369} & \frac{-145200}{1369}\\
100 & 200 & -100 \\
\frac{-4902900}{58867} & \frac{-9821500}{58867} & \frac{4921300}{58867} \\
\end{bmatrix}
$$
Weźmy $p=q=1$

Czyli $||A||_{1,1} = \max_{1<i<n} \sum_{j=1}^n|a_{ij}|$

$
||A|| = \max(4.63, 6.16, 11.12)
$

$
||A^{-1}|| = \max(424.18, \dots, \dots) \ge 424.18
$

Więc $K_{11} = ||A^{-1}|| \cdot ||A|| \ge 11.12 \cdot 424.18 >> 1 $

A zatem jest to macierz źle uwarunkowana

c) $det(A) = 4$

$$
A^{-1} = 
\begin{bmatrix}
\frac{3}{4} & \frac{1}{2} & \frac{1}{4}\\
\frac{1}{2}  & 1 & \frac{1}{2}  \\
\frac{1}{4} & \frac{1}{2} & \frac{3}{4} \\
\end{bmatrix}
$$

$
||A|| = \max(3, 4, 3) = 4
$

$
||A^{-1}|| = \max(1.5, 2, 1.5)
$

Więc $K_{11} = 8$

Zatem macierz jest dość dobrze uwarunkowana.

d) $det(A) = 0$ -> macierz osobliwa

Zadanie 2

$A = LU$

Więc

$det(A) = det(L) \cdot det(U)$

In [3]:
def swap_rows(mat, i, j):
    n = len(mat[0])
    for k in range(n):
        temp = mat[i][k]
        mat[i][k] = mat[j][k]
        mat[j][k] = temp

In [4]:
def rozwiazanie(mat):
    m = len(mat)
    n = len(mat[0])
    wyniki = np.zeros(m)
    for i in range(m-1,-1,-1):
        wyniki[i] = mat[i][m]
        for j in range(i+1,m):
            wyniki[i] -= mat[i][j] * wyniki[j]
        wyniki[i] = (wyniki[i]/mat[i][i])
    return wyniki


In [5]:
def gauss(mat):
    swap_count = 0
    mat = np.array(mat, dtype=float)
    m = len(mat)
    n = len(mat[0])
    h = 0
    k = 0
    while h < m and k < n:
        i_max = np.argmax(np.abs(mat[h:, k])) + h
        if mat[i_max, k] == 0:
            k += 1
        else:
            if i_max != h:
                swap_rows(mat, h, i_max)
                swap_count += 1
            for i in range(h+1, m):
                f = mat[i, k] / mat[h, k]
                mat[i, k] = 0
                for j in range(k+1, n):
                    mat[i,j] = mat[i,j] - mat[h,j] * f
            h += 1
            k += 1
    return mat, swap_count
            
    
            


In [6]:
def determinant_of_triangular_matrix(mat, swap_count):
    n = len(mat)
    wynik = 1
    for i in range(n):
        wynik *= mat[i][i]
    return wynik * (-1) ** swap_count

In [7]:
def gauss_jordan(mat):
    swap_count = 0
    mat = np.array(mat, dtype=float)
    m = len(mat)
    n = len(mat[0])
    h = 0
    k = 0
    while h < m and k < n:
        i_max = np.argmax(np.abs(mat[h:, k])) + h
        if mat[i_max, k] == 0:
            k += 1
        else:
            if i_max != h:
                swap_rows(mat, h, i_max)
                swap_count += 1
            for i in range(h+1, m):
                f = mat[i, k] / mat[h, k]
                mat[i, k] = 0
                for j in range(k+1, n):
                    mat[i,j] = mat[i,j] - mat[h,j] * f
            h += 1
            k += 1
    for i in range(m-1, -1, -1):
        j = np.argmax(np.abs(mat[i]))
        mat[i] /= mat[i][j]
        for k in range(i-1, -1, -1):
            mat[k] -= mat[i] * mat[k][j]
    return mat, swap_count
            


In [8]:
def inversing(mat):
    mat = np.array(mat, dtype=float)
    m = len(mat)
    n = len(mat[0])
    if m != n:
        raise(ValueError("Macierz musi byc kwadratowa"))
    if determinant_of_triangular_matrix(gauss(mat)[0], gauss(mat)[1]) == 0:
        raise(ValueError("Macierz jest osobliwa i nie ma odwrotności"))
    h = 0
    mat_inv = np.eye(m)
    while h < m:
        i_max = np.argmax(np.abs(mat[h:, h])) + h
        if mat[i_max, h] == 0:
            raise(ValueError("Macierz jest osobliwa i nie ma odwrotności"))
        else:
            if i_max != h:
                swap_rows(mat, h, i_max)
                swap_rows(mat_inv, h, i_max)

            for i in range(h+1, m):
                f = mat[i, h] / mat[h, h]
                mat[i, h] = 0
                mat_inv[i] -= mat_inv[h] * f
                for j in range(h+1, n):
                    mat[i,j] -= mat[h,j] * f
            h += 1
    for i in range(n - 1, -1, -1):
        mat_inv[i] /= mat[i, i]
        mat[i] /= mat[i, i]  
        for k in range(i):
            mat_inv[k] -= mat_inv[i] * mat[k, i]
            mat[k] -= mat[i] * mat[k,i]
    return mat_inv, mat
            


Zadanie 4

In [142]:
A = np.array([
    [0, 0, 2, 1, 2],
    [0, 1, 0, 2, -1],
    [1, 2, 0, -2, 0],
    [0, 0, 0, -1, 1],
    [0, 1, -1, 1, -1]
])

b = np.array([1, 1, -4, -2, -1])

augmented_matrix = np.column_stack((A, b))

In [143]:
print(gauss(augmented_matrix))
print(rozwiazanie(gauss(augmented_matrix)[0]))

(array([[ 1. ,  2. ,  0. , -2. ,  0. , -4. ],
       [ 0. ,  1. ,  0. ,  2. , -1. ,  1. ],
       [ 0. ,  0. ,  2. ,  1. ,  2. ,  1. ],
       [ 0. ,  0. ,  0. , -1. ,  1. , -2. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5, -0.5]]), 1)
[ 2. -2.  1.  1. -1.]


Zadanie 5

In [144]:
A = np.array([
    [1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
    [1, 3, 9, 27, 81],
    [1, 5, 25, 125, 625],
    [1, 6, 36, 216, 1296]
])

b = np.array([-1, 1, 3, 2, -2])

augmented_matrix = np.column_stack((A, b))

In [146]:
print(rozwiazanie(gauss(augmented_matrix)[0]))

[-1.          2.68333333 -0.875       0.21666667 -0.025     ]


Zadanie 6

In [147]:
A = np.array([
    [3.5, 2.77, -0.76, 1.8],
    [-1.8, 2.68, 3.44, -0.09],
    [0.27, 5.07, 6.9, 1.61],
    [1.71, 5.45, 2.68, 1.71],
], dtype=float)

b = np.array([7.31, 4.23, 13.85, 11.55])

augmented_matrix = np.column_stack((A, b))

In [148]:
x = rozwiazanie(gauss(augmented_matrix)[0])
print(x)

[1. 1. 1. 1.]


In [149]:
print(f"det(A) = {determinant_of_triangular_matrix(gauss(A)[0], gauss(A)[1])}")

det(A) = -0.22579734000000884


In [150]:
Ax = np.dot(A, x)
print(f"Ax = {Ax}")

Ax = [ 7.31  4.23 13.85 11.55]


In [151]:
r = b - Ax
print(f"r = {r}")

r = [8.88178420e-16 0.00000000e+00 1.77635684e-15 1.77635684e-15]


Na podstawie wektora reszt można wywnioskować, że wszystkie wyniki są obliczone z dużą dokładnością (błąd jest mały, rzędu $10^{-15}$ i $10^{-16}$). Rozwiązanie $x_2$ jest najbardziej dokadne.

Zadanie 7

In [83]:
A = np.array([
    [10, -2, -1, 2, 3, 1, -4, 7],
    [5, 11, 3, 10, -3, 3, 3, -4],
    [7, 12, 1, 5, 3, -12, 2, 3],
    [8, 7, -2, 1, 3, 2, 2, 4],
    [2, -15, -1, 1, 4, -1, 8, 3],
    [4, 2, 9, 1, 12, -1, 4, 1],
    [-1, 4, -7, -1, 1, 1, -1, -3],
    [-1, 3, 4, 1, 3, -4, 7, 6]
], dtype=float)

b = np.array([0, 12, -5, 3, -25, -26, 9, -7])

augmented_matrix = np.column_stack((A, b))

In [84]:
x = rozwiazanie(gauss(augmented_matrix)[0])
print(x)

[-1.  1. -1.  1. -1.  1. -1.  1.]


Zadanie 8

In [16]:
def inversing(mat):
    mat = np.array(mat, dtype=float)
    m = len(mat)
    n = len(mat[0])
    if m != n:
        raise(ValueError("Macierz musi byc kwadratowa"))
    if np.isclose(determinant_of_triangular_matrix(gauss(mat)[0], gauss(mat)[1]), 0):
        raise(ValueError("Macierz jest osobliwa i nie ma odwrotności"))
    h = 0
    mat_inv = np.eye(m)
    while h < m:
        i_max = np.argmax(np.abs(mat[h:, h])) + h
        if mat[i_max, h] == 0:
            raise(ValueError("Macierz jest osobliwa i nie ma odwrotności"))
        else:
            if i_max != h:
                swap_rows(mat, h, i_max)
                swap_rows(mat_inv, h, i_max)

            for i in range(h+1, m):
                f = mat[i, h] / mat[h, h]
                mat[i, h] = 0
                mat_inv[i] -= mat_inv[h] * f
                for j in range(h+1, n):
                    mat[i,j] -= mat[h,j] * f
            h += 1
    for i in range(n - 1, -1, -1):
        mat_inv[i] /= mat[i, i]
        mat[i] /= mat[i, i]  
        for k in range(i):
            mat_inv[k] -= mat_inv[i] * mat[k, i]
            mat[k] -= mat[i] * mat[k,i]
    return mat_inv
            


In [134]:
A = np.array([
    [2, -1, 0, 0, 0, 0],
    [-1, 2, -1, 0, 0, 0],
    [0, -1, 2, -1, 0, 0],
    [0, 0, -1, 2, -1, 0],
    [0, 0, 0, -1, 2, -1],
    [0, 0, 0, 0, -1, 5]
], dtype=float)


In [135]:
print((inversing(A)))

[[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]


Nie jest trójdiagonalna

Zadanie 9

In [9]:
A = np.array([
    [1, 3, -9, 6, 4],
    [2, -1, 6, 7, 1],
    [3, 2, -3, 15, 5],
    [8, -1, 1, 4, 2],
    [11, 1, -2, 18, 7]
], dtype=float)


In [17]:
print((inversing(A)))

ValueError: Macierz jest osobliwa i nie ma odwrotności

In [13]:
print(determinant_of_triangular_matrix(gauss(A)[0], gauss(A)[1]))

5.928590951498336e-14


In [139]:
print(np.linalg.det(A))

1.9761969838327938e-14


Wyznacznik tej macierzy powinien być równy zero, lecz przez pewne przybliżenia wykonywane przez komputer - nie jest. Liczona zatem jest macierz odwrotna z macierzy osobliwej, która jest nieodwracalna. Wynik nie jest prawdziwy.