In [2]:
import numpy as np
import scipy

In [10]:
def swap_rows(mat, i, j):
    n = len(mat[0])
    for k in range(n):
        temp = mat[i][k]
        mat[i][k] = mat[j][k]
        mat[j][k] = temp

In [42]:
mat = [[1,2,3,6], [4,5,6,7],[2,3,4,9]]


In [25]:
print(np.argmax(mat, axis=0))

[1 1 1 2]


In [45]:
def gauss(mat):
    mat = np.array(mat)
    m = len(mat)
    n = len(mat[0])
    h = 0
    k = 0
    while h < m and k < n:
        i_max = np.argmax(np.abs(mat[h:, k])) + h
        if mat[i_max, k] == 0:
            k += 1
        else:
            if i_max != h:
                swap_rows(mat, h, i_max)
            for i in range(h+1, m):
                f = mat[i, k] / mat[h, k]
                mat[i, k] = 0
                for j in range(k+1, n):
                    mat[i,j] = mat[i,j] - mat[h,j] * f
            h += 1
            k += 1
    return mat
            
    
            


In [46]:
print(gauss(mat))

[[4 5 6 7]
 [0 0 1 4]
 [0 0 0 1]]


In [ ]:
def rozwiazanie(mat):
    m = len(mat)
    n = len(mat[0])

Zadanie 4

In [48]:
A = np.array([
    [0, 0, 2, 1, 2],
    [0, 1, 0, 2, -1],
    [1, 2, 0, -2, 0],
    [0, 0, 0, -1, 1],
    [0, 1, -1, 1, -1]
])

b = np.array([1, 1, -4, -2, -1])

augmented_matrix = np.column_stack((A, b))

In [49]:
print(gauss(augmented_matrix))

[[ 1  2  0 -2  0 -4]
 [ 0  1  0  2 -1  1]
 [ 0  0  2  1  2  1]
 [ 0  0  0 -1  1 -2]
 [ 0  0  0  0  1 -1]]
