In [2]:
import numpy as np
import scipy

In [10]:
def swap_rows(mat, i, j):
    n = len(mat[0])
    for k in range(n):
        temp = mat[i][k]
        mat[i][k] = mat[j][k]
        mat[j][k] = temp

In [42]:
mat = [[1,2,3,6], [4,5,6,7],[2,3,4,9]]


In [25]:
print(np.argmax(mat, axis=0))

[1 1 1 2]


In [85]:
def rozwiazanie(mat):
    m = len(mat)
    n = len(mat[0])
    wyniki = np.zeros(5)
    for i in range(m-1,-1,-1):
        wyniki[i] = mat[i][m]
        for j in range(i+1,m):
            wyniki[i] -= mat[i][j] * wyniki[j]
        wyniki[i] = (wyniki[i]/mat[i][i])
    return wyniki

In [86]:
def gauss(mat):
    mat = np.array(mat)
    m = len(mat)
    n = len(mat[0])
    h = 0
    k = 0
    while h < m and k < n:
        i_max = np.argmax(np.abs(mat[h:, k])) + h
        if mat[i_max, k] == 0:
            k += 1
        else:
            if i_max != h:
                swap_rows(mat, h, i_max)
            for i in range(h+1, m):
                f = mat[i, k] / mat[h, k]
                mat[i, k] = 0
                for j in range(k+1, n):
                    mat[i,j] = mat[i,j] - mat[h,j] * f
            h += 1
            k += 1
    return mat
            
    
            


In [87]:
print(gauss(mat))

[[4 5 6 7]
 [0 0 1 4]
 [0 0 0 1]]


Zadanie 4

In [88]:
A = np.array([
    [0, 0, 2, 1, 2],
    [0, 1, 0, 2, -1],
    [1, 2, 0, -2, 0],
    [0, 0, 0, -1, 1],
    [0, 1, -1, 1, -1]
])

b = np.array([1, 1, -4, -2, -1])

augmented_matrix = np.column_stack((A, b))

In [89]:

print(gauss(augmented_matrix))
print(rozwiazanie(gauss(augmented_matrix)))



[[ 1  2  0 -2  0 -4]
 [ 0  1  0  2 -1  1]
 [ 0  0  2  1  2  1]
 [ 0  0  0 -1  1 -2]
 [ 0  0  0  0  1 -1]]
[ 2. -2.  1.  1. -1.]


Zadanie 5

In [93]:
A = np.array([
    [1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
    [1, 3, 9, 27, 81],
    [1, 5, 25, 125, 625],
    [1, 6, 36, 256, 1296]
])

b = np.array([-1, 1, 3, 2, -2])

augmented_matrix = np.column_stack((A, b))

In [94]:

print(gauss(augmented_matrix))
print(rozwiazanie(gauss(augmented_matrix)))



[[   1    0    0    0    0   -1]
 [   0    6   36  256 1296   -1]
 [   0    0   -9 -101 -567    4]
 [   0    0    0  -31 -140    0]
 [   0    0    0    0   32    0]]
[-1.          2.5        -0.44444444 -0.          0.        ]


In [92]:
#Pozostałe zadania powinny zostać rozwiązane przy pomocy własnej im- plementacji metody 
# eliminacji Gaussa z częściowym wyborem elementu podstawowego oraz dla porównania - przy 
# pomocy funkcji w bibliotece scipy.
 
import numpy as np
 
def gauSS(macierz_a,macierz_b):
    pierwszy_a = macierz_a.shape[0]
    if macierz_a.shape[1] != pierwszy_a:
        print('Jesteś debilem')
        return
    if macierz_b.shape[1] > 1 or macierz_b.shape[0] != macierz_a.shape[0]:
        print('Jesteś jeszcze większym debilem')
        return
 
    n = len(macierz_b)
    m = n-1
    i = 0
    j = i-1 
    x = np.zeros(n)
 
    macierz_rozszerzona = np.concatenate((macierz_a,macierz_b),axis=1,dtype=float)
    while i < n:
        if macierz_rozszerzona[0][0] == 0.0:
            for c in range(i+1,n):
                nierzad = macierz_rozszerzona[c].copy()
                szukana_wartosc = macierz_rozszerzona[c][0]
                if szukana_wartosc != 0.0:
                    macierz_rozszerzona[c] = macierz_rozszerzona[0]
                    macierz_rozszerzona[0] = nierzad
                    print(macierz_rozszerzona)
                    break
                else:
                    if c == n-1:
                        print('Coś nie pykło z przekątną')
                        return 
        for j in range(i+1,n):
            czynnik = macierz_rozszerzona[j][i]/macierz_rozszerzona[i][i]
            macierz_rozszerzona[j] = macierz_rozszerzona[j] - (czynnik*macierz_rozszerzona[i])
        i+=1
    print(macierz_rozszerzona)
    x[m] = macierz_rozszerzona[m][n]/macierz_rozszerzona[m][m]
    for k in range(n-2,-1,-1):
        x[k] = macierz_rozszerzona[k][n]
        for j in range(k+1,n):
            x[k] /= macierz_rozszerzona[k][k]
    for p in range(n):
        print(f'x{p}={x[p]}')
 
 
#zad4
print("zad4")
gauSS(np.array([[0,0,2,1,2],[0,1,0,2,-1],[1,2,0,-2,0],[0,0,0,-1,1],[0,1,-1,1,-1]]),np.array([[1],[1],[-4],[-2],[-1]]))
#zad6
print("zad6")
gauSS(np.array([[3.5,2.77,-0.76,1.8],[-1.8,2.68,3.44,-0.09],[0.27,5.07,6.9,1.61],[1.71,5.45,2.68,1.71]]),np.array([[7.31],[4.23],[13.85],[11.55]]))
#zad7
gauSS(np.array([[10,-2,-1,2,3,1,-4,7],[5,11,3,10,-3,3,3,-4],[7,12,1,5,3,-12,2,3],[8,7,-2,1,3,2,2,4],[2,-15,-1,1,4,-1,8,3],[4,2,9,1,12,-1,4,1],[-1,4,-7,-1,1,1,-1,-3],[-1,3,4,1,3,-4,7,6]]),np.array([[0],[12],[-5],[3],[-25],[-26],[9],[-7]]))
#zad5
gauSS(np.array([[1,0,0,0,0],[1,1,1,1,1],[1,3,9,27,81],[1,5,25,125,625],[1,6,36,216,1296]]),np.array([[-1],[1],[3],[2],[-2]]))

zad4
[[ 1.  2.  0. -2.  0. -4.]
 [ 0.  1.  0.  2. -1.  1.]
 [ 0.  0.  2.  1.  2.  1.]
 [ 0.  0.  0. -1.  1. -2.]
 [ 0.  1. -1.  1. -1. -1.]]
[[ 1.   2.   0.  -2.   0.  -4. ]
 [ 0.   1.   0.   2.  -1.   1. ]
 [ 0.   0.   2.   1.   2.   1. ]
 [ 0.   0.   0.  -1.   1.  -2. ]
 [ 0.   0.   0.   0.   0.5 -0.5]]
x0=-4.0
x1=1.0
x2=0.25
x3=2.0
x4=-1.0
zad6
[[ 3.50000000e+00  2.77000000e+00 -7.60000000e-01  1.80000000e+00
   7.31000000e+00]
 [ 2.22044605e-16  4.10457143e+00  3.04914286e+00  8.35714286e-01
   7.98942857e+00]
 [-2.62711566e-16  0.00000000e+00  3.35104218e+00  4.82369414e-01
   3.83341160e+00]
 [-2.20985318e-16  0.00000000e+00  0.00000000e+00 -4.69032638e-03
  -4.69032638e-03]]
x0=0.1704956268221574
x1=0.4742202365792094
x2=1.1439460882798778
x3=0.9999999999999036
[[ 1.00000000e+01 -2.00000000e+00 -1.00000000e+00  2.00000000e+00
   3.00000000e+00  1.00000000e+00 -4.00000000e+00  7.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  1.20000000e+01  3.50000000e+00  9.00000000e+00
  -4