In [2]:
import numpy as np
import scipy

In [4]:
def swap_rows(mat, i, j):
    n = len(mat[0])
    for k in range(n):
        temp = mat[i][k]
        mat[i][k] = mat[j][k]
        mat[j][k] = temp

In [5]:
def rozwiazanie(mat):
    m = len(mat)
    n = len(mat[0])
    wyniki = np.zeros(m)
    for i in range(m-1,-1,-1):
        wyniki[i] = mat[i][m]
        for j in range(i+1,m):
            wyniki[i] -= mat[i][j] * wyniki[j]
        wyniki[i] = (wyniki[i]/mat[i][i])
    return wyniki


In [22]:
def gauss(mat):
    swap_count = 0
    mat = np.array(mat, dtype=float)
    m = len(mat)
    n = len(mat[0])
    h = 0
    k = 0
    while h < m and k < n:
        i_max = np.argmax(np.abs(mat[h:, k])) + h
        if mat[i_max, k] == 0:
            k += 1
        else:
            if i_max != h:
                swap_rows(mat, h, i_max)
                swap_count += 1
            for i in range(h+1, m):
                f = mat[i, k] / mat[h, k]
                mat[i, k] = 0
                for j in range(k+1, n):
                    mat[i,j] = mat[i,j] - mat[h,j] * f
            h += 1
            k += 1
    return mat, swap_count
            
    
            


In [28]:
def determinant_of_triangular_matrix(mat, swap_count):
    n = len(mat)
    wynik = 1
    for i in range(n):
        wynik *= mat[i][i]
    return wynik * (-1) ** swap_count

Zadanie 4

In [23]:
A = np.array([
    [0, 0, 2, 1, 2],
    [0, 1, 0, 2, -1],
    [1, 2, 0, -2, 0],
    [0, 0, 0, -1, 1],
    [0, 1, -1, 1, -1]
])

b = np.array([1, 1, -4, -2, -1])

augmented_matrix = np.column_stack((A, b))

In [25]:

print(gauss(augmented_matrix))
print(rozwiazanie(gauss(augmented_matrix)[0]))



(array([[ 1. ,  2. ,  0. , -2. ,  0. , -4. ],
       [ 0. ,  1. ,  0. ,  2. , -1. ,  1. ],
       [ 0. ,  0. ,  2. ,  1. ,  2. ,  1. ],
       [ 0. ,  0. ,  0. , -1. ,  1. , -2. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5, -0.5]]), 1)
[ 2. -2.  1.  1. -1.]


Zadanie 5

In [26]:
A = np.array([
    [1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1],
    [1, 3, 9, 27, 81],
    [1, 5, 25, 125, 625],
    [1, 6, 36, 216, 1296]
])

b = np.array([-1, 1, 3, 2, -2])

augmented_matrix = np.column_stack((A, b))

In [27]:

print(gauss(augmented_matrix))
print(rozwiazanie(gauss(augmented_matrix)[0]))



(array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  6.00000000e+00,  3.60000000e+01,
         2.16000000e+02,  1.29600000e+03, -1.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -9.00000000e+00,
        -8.10000000e+01, -5.67000000e+02,  4.50000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.00000000e+01, -1.40000000e+02,  1.33333333e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -4.00000000e+01,  1.00000000e+00]]), 1)
[-1.          2.68333333 -0.875       0.21666667 -0.025     ]


Zadanie 6

In [35]:
A = np.array([
    [3.5, 2.77, -0.76, 1.8],
    [-1.8, 2.68, 3.44, -0.09],
    [0.27, 5.07, 6.9, 1.61],
    [1.71, 5.45, 2.68, 1.71],
], dtype=float)

b = np.array([7.31, 4.23, 13.85, 11.55])

augmented_matrix = np.column_stack((A, b))

In [36]:
print(gauss(augmented_matrix))
x = rozwiazanie(gauss(augmented_matrix)[0])
print(x)

(array([[ 3.50000000e+00,  2.77000000e+00, -7.60000000e-01,
         1.80000000e+00,  7.31000000e+00],
       [ 0.00000000e+00,  4.85631429e+00,  6.95862857e+00,
         1.47114286e+00,  1.32860857e+01],
       [ 0.00000000e+00,  0.00000000e+00, -2.83231092e+00,
        -4.07700078e-01, -3.24001100e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -4.69032638e-03, -4.69032638e-03]]), 1)
[1. 1. 1. 1.]


In [33]:
print(determinant_of_triangular_matrix(gauss(A)[0], gauss(A)[1]))

-0.22579734000000884


In [38]:
Ax = np.dot(A, x)
print(Ax)

[ 7.31  4.23 13.85 11.55]


In [40]:
r = b - Ax
print(r)

[8.88178420e-16 0.00000000e+00 1.77635684e-15 1.77635684e-15]


Na podstawie wektora reszt można wywnioskować, że wszystkie wyniki są obliczone z dużą dokładnością (błąd jest mały, rzędu $10^{-15}$ i $10^{-16}$). Rozwiązanie $x_2$ jest najbardziej dokadne.

Zadanie 7