# Metody numeryczne
## Wykład 2 - układy równań liniowych
### Janusz Szwabiński

## Eliminacja Gaussa

In [1]:
import numpy as np

def gaussElimin(a,b):
    n = len(b)
    # Elimination phase
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a [i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
    # Back substitution
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [2]:
a = np.array([[4.0,-2,1],[-2,4,-2],[1,-2,4]],dtype='float64')

In [3]:
b = np.array([11.0,-16,17])

In [4]:
x = gaussElimin(np.copy(a),np.copy(b))

In [5]:
x

array([ 1., -2.,  3.])

In [6]:
np.dot(a,x)

array([ 11., -16.,  17.])

In [7]:
np.linalg.solve(a,b)

array([ 1., -2.,  3.])

## Brak niezawodności

In [8]:
a2 = np.array([[1,0,1],[1,1,1],[1,-1,1]],dtype='float64')

In [9]:
b2 = np.array([2,3,1],dtype='float64')

In [10]:
np.linalg.det(a2)

np.float64(0.0)

In [11]:
x = gaussElimin(np.copy(a2),np.copy(b2))

/tmp/ipykernel_22744/1085182043.py:14: RuntimeWarning: invalid value encountered in scalar divide
  b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]


## Układy niedookreślone

In [4]:
import scipy as sp
import numpy as np
b = np.mat('[3]')
A = np.mat('[1 2]')
AI = sp.linalg.pinv(A)
AI*b


matrix([[0.6],
        [1.2]])

## Układy nadokreślone

In [5]:
c = np.mat ('[1.98; 0.95; 3.98; 0.92;2.90]')
B = np.mat ('[1 1;2.05 -1;3.06 1; -1.02 2;4.08 -1]')
BI = sp.linalg.pinv(B)
BI*c

matrix([[0.9631014 ],
        [0.98854334]])

In [6]:
#bezpośrednio z metody najmniejszych kwadratów
x,res,rank,s = sp.linalg.lstsq(B,c)
x

array([[0.9631014 ],
       [0.98854334]])

In [7]:
help(sp.linalg.lstsq)

Help on function lstsq in module scipy.linalg._basic:

lstsq(a, b, cond=None, overwrite_a=False, overwrite_b=False, check_finite=True, lapack_driver=None)
    Compute least-squares solution to equation Ax = b.
    
    Compute a vector x such that the 2-norm ``|b - A x|`` is minimized.
    
    Parameters
    ----------
    a : (M, N) array_like
        Left-hand side array
    b : (M,) or (M, K) array_like
        Right hand side array
    cond : float, optional
        Cutoff for 'small' singular values; used to determine effective
        rank of a. Singular values smaller than
        ``cond * largest_singular_value`` are considered zero.
    overwrite_a : bool, optional
        Discard data in `a` (may enhance performance). Default is False.
    overwrite_b : bool, optional
        Discard data in `b` (may enhance performance). Default is False.
    check_finite : bool, optional
        Whether to check that the input matrices contain only finite numbers.
        Disabling may giv